[project]
name = "shared"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "codecarbon>=3.0.2",
    "google-cloud-storage>=3.1.1",
    "mlflow>=3.1.0",
]
